version: '3'
services:
  web:
    build: ./cloud_app
    command: bash -c "python3 ./manage.py runserver 0.0.0.0:8000 && python3 ./manage.py migrate && celery -A cloud_app worker -l info"
    ports:
    - 8000:8000
    volumes:
    - ./cloud_app:/data
    depends_on:
    - db
    - cost_service
    - redis
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres@db/postgres
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  cost_service:
    image: cost_s6
    ports:
      - 5000:5000

  db:
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
