# Generated by Django 3.0.8 on 2020-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('hdd_type', models.CharField(choices=[('sata', 'sata'), ('ssd', 'ssd'), ('sas', 'sas')], max_length=15)),
                ('hdd_capacity', models.IntegerField()),
            ],
        ),
    ]
