# Generated by Django 3.1 on 2020-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200814_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='virtual_machines',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='networks',
            field=models.ManyToManyField(to='core.Network'),
        ),
    ]
