# Generated by Django 3.1 on 2020-09-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdditionalHdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('hdd_type', models.CharField(choices=[('sata', 'sata'), ('ssd', 'ssd'), ('sas', 'sas')], max_length=15, verbose_name='Тип жёсткого диска')),
                ('hdd_capacity', models.IntegerField(verbose_name='Объём памяти жёсткого диска')),
                ('cost', models.IntegerField(default=0)),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.virtualmachine')),
            ],
        ),
    ]
