# Generated by Django 3.1 on 2020-09-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200926_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.AddField(
            model_name='report',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='most_additional_hdds_by_capacity',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='report',
            name='most_additional_hdds_by_number',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='report',
            name='most_capacious',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='report',
            name='most_cheapest',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='report',
            name='most_expensive',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
