# Generated by Django 3.1 on 2020-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200930_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='csv_id',
            field=models.IntegerField(default=0),
        ),
    ]
