# Generated by Django 3.1 on 2020-09-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_virtualmachine_csv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalhdd',
            name='csv_id',
            field=models.IntegerField(default=0),
        ),
    ]
